from datetime import datetime, timezone
import os
import secrets
from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session

from app import models, schemas
from app.audit import log_event
from app.auth import get_current_user, require_role
from app.consent import get_latest_consent
from app.database import get_db
from app.email import email_service

router = APIRouter(prefix="/consents", tags=["Consents"])


def _consent_action_base_url() -> str:
    return os.getenv("CONSENT_ACTION_BASE_URL", "http://localhost:8000").rstrip("/")


@router.post("/patients/{patient_id}/request-email", response_model=schemas.ConsentRequestResult, status_code=201)
def request_consent_email(
    patient_id: int,
    body: schemas.ConsentRequestCreate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(
        require_role(models.UserRole.admin, models.UserRole.doctor, models.UserRole.nurse)
    ),
):
    patient = db.query(models.Patient).filter(models.Patient.id == patient_id).first()
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")

    token = secrets.token_urlsafe(32)
    consent = models.Consent(
        patient_id=patient_id,
        status=models.ConsentStatus.pending,
        basis=body.basis,
        notes=body.notes,
        contact_first_name=body.first_name,
        contact_last_name=body.last_name,
        contact_email=body.email,
        contact_phone=body.phone,
        relationship=body.relationship,
        contact_address=body.address,
        action_token=token,
        expires_at=body.expires_at,
        captured_by=current_user.id,
    )
    db.add(consent)
    db.commit()
    db.refresh(consent)

    base_url = _consent_action_base_url()
    yes_link = f"{base_url}/consents/respond?token={token}&decision=yes"
    no_link = f"{base_url}/consents/respond?token={token}&decision=no"

    subject = f"Consent Request for {patient.full_name}"
    plain = (
        f"Dear {body.first_name} {body.last_name},\n\n"
        f"You have been requested to provide consent for patient: {patient.full_name}.\n"
        f"Relationship: {body.relationship}\n"
        f"Reason/Basis: {body.basis}\n\n"
        f"To approve consent, click: {yes_link}\n"
        f"To decline consent, click: {no_link}\n\n"
        "This link is generated by MedSuite Hospital Management System."
    )
    html = f"""
    <html>
      <body style=\"font-family: Arial, sans-serif; line-height: 1.5; color: #111827;\">
        <div style=\"max-width: 700px; margin: 24px auto; padding: 18px; border: 1px solid #e5e7eb; border-radius: 10px;\">
          <h2 style=\"margin: 0 0 8px; color: #1e3a5f;\">Consent Request</h2>
          <p>Hello <strong>{body.first_name} {body.last_name}</strong>,</p>
          <p>Please provide consent for patient: <strong>{patient.full_name}</strong>.</p>
          <p><strong>Relationship:</strong> {body.relationship}<br/>
             <strong>Basis:</strong> {body.basis}</p>
          <div style=\"display: flex; gap: 12px; margin-top: 16px;\">
            <a href=\"{yes_link}\" style=\"text-decoration: none; background: #16a34a; color: white; padding: 10px 16px; border-radius: 8px; font-weight: 600;\">Yes, I Consent</a>
            <a href=\"{no_link}\" style=\"text-decoration: none; background: #dc2626; color: white; padding: 10px 16px; border-radius: 8px; font-weight: 600;\">No, I Do Not Consent</a>
          </div>
          <p style=\"margin-top: 16px; color: #6b7280; font-size: 12px;\">If you did not expect this request, please ignore this email.</p>
        </div>
      </body>
    </html>
    """

    email_sent = email_service.send_email(body.email, subject, plain, html)
    consent.email_sent = email_sent
    db.commit()
    db.refresh(consent)

    log_event(
        db,
        action="consent.request_sent",
        entity_type="consent",
        entity_id=consent.id,
        actor_user_id=current_user.id,
        patient_id=patient_id,
        details={"to": body.email, "email_sent": email_sent},
        commit=True,
    )

    return schemas.ConsentRequestResult(
        consent=consent,
        email_sent=email_sent,
        action_url_sent_to=body.email,
    )


@router.get("/respond", response_class=HTMLResponse)
def respond_to_consent_request(
    token: str = Query(...),
    decision: str = Query(...),
    db: Session = Depends(get_db),
):
    consent = db.query(models.Consent).filter(models.Consent.action_token == token).first()
    if not consent:
        return HTMLResponse("<h3>Invalid or expired consent link.</h3>", status_code=404)

    decision_normalized = decision.strip().lower()
    if consent.status in {models.ConsentStatus.active, models.ConsentStatus.declined}:
        return HTMLResponse("<h3>This consent request has already been processed.</h3>")

    now = datetime.now(timezone.utc)
    if decision_normalized in {"yes", "approve", "approved", "true"}:
        consent.status = models.ConsentStatus.active
        consent.responded_at = now
        consent.captured_at = now
        outcome = "approved"
    elif decision_normalized in {"no", "decline", "declined", "false"}:
        consent.status = models.ConsentStatus.declined
        consent.responded_at = now
        outcome = "declined"
    else:
        return HTMLResponse("<h3>Invalid decision parameter. Use yes or no.</h3>", status_code=400)

    db.commit()
    db.refresh(consent)

    log_event(
        db,
        action=f"consent.response_{outcome}",
        entity_type="consent",
        entity_id=consent.id,
        patient_id=consent.patient_id,
        details={
            "decision": outcome,
            "actor": "email_link",
            "contact_email": consent.contact_email,
            "contact_name": f"{consent.contact_first_name} {consent.contact_last_name}".strip(),
        },
        commit=True,
    )

    card_color = "#16a34a" if outcome == "approved" else "#dc2626"
    action_text = "approved" if outcome == "approved" else "declined"
    return HTMLResponse(
        f"""
        <html><body style='font-family: Arial, sans-serif; background: #f8fafc;'>
          <div style='max-width: 560px; margin: 60px auto; background: white; padding: 24px; border-radius: 12px; border: 1px solid #e5e7eb;'>
            <h2 style='margin-top:0;color:#1e3a5f'>Consent Response Received</h2>
            <p>Your consent has been <strong style='color:{card_color}'>{action_text}</strong>.</p>
            <p style='color:#6b7280'>Thank you. You can close this page.</p>
          </div>
        </body></html>
        """
    )


@router.post("/patients/{patient_id}", response_model=schemas.ConsentOut, status_code=201)
def grant_consent(
    patient_id: int,
    body: schemas.ConsentCreate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(
        require_role(models.UserRole.admin, models.UserRole.doctor, models.UserRole.nurse)
    ),
):
    patient = db.query(models.Patient).filter(models.Patient.id == patient_id).first()
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")

    # Auto-expire old active consent records.
    old_records = (
        db.query(models.Consent)
        .filter(models.Consent.patient_id == patient_id, models.Consent.status == models.ConsentStatus.active)
        .all()
    )
    now = datetime.now(timezone.utc)
    for item in old_records:
        item.status = models.ConsentStatus.expired
        if item.revoked_at is None:
            item.revoked_at = now
            item.revoked_by = current_user.id

    consent = models.Consent(
        patient_id=patient_id,
        status=models.ConsentStatus.active,
        basis=body.basis,
        notes=body.notes,
        expires_at=body.expires_at,
        captured_by=current_user.id,
    )
    db.add(consent)
    db.commit()
    db.refresh(consent)

    log_event(
        db,
        action="consent.granted",
        entity_type="consent",
        entity_id=consent.id,
        actor_user_id=current_user.id,
        patient_id=patient_id,
        details={"basis": consent.basis, "expires_at": str(consent.expires_at) if consent.expires_at else None},
        commit=True,
    )

    return consent


@router.post("/patients/{patient_id}/revoke", response_model=schemas.ConsentOut)
def revoke_consent(
    patient_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(
        require_role(models.UserRole.admin, models.UserRole.doctor)
    ),
):
    consent = get_latest_consent(db, patient_id)
    if not consent:
        raise HTTPException(status_code=404, detail="Consent not found")

    consent.status = models.ConsentStatus.revoked
    consent.revoked_by = current_user.id
    consent.revoked_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(consent)

    log_event(
        db,
        action="consent.revoked",
        entity_type="consent",
        entity_id=consent.id,
        actor_user_id=current_user.id,
        patient_id=patient_id,
        commit=True,
    )

    return consent


@router.get("/patients/{patient_id}", response_model=schemas.ConsentOut)
def latest_consent(
    patient_id: int,
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    consent = get_latest_consent(db, patient_id)
    if not consent:
        raise HTTPException(status_code=404, detail="Consent not found")
    return consent


@router.get("/patients/{patient_id}/history", response_model=List[schemas.ConsentOut])
def consent_history(
    patient_id: int,
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    return (
        db.query(models.Consent)
        .filter(models.Consent.patient_id == patient_id)
        .order_by(models.Consent.captured_at.desc())
        .all()
    )
