"""add_uhid_column

Revision ID: add_uhid_column_v1
Revises: d0b9eb7f28e4
Create Date: 2026-03-14 00:00:00.000000

"""
from typing import Sequence, Union
from datetime import datetime
import secrets

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_uhid_column_v1'
down_revision: Union[str, None] = 'd0b9eb7f28e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def generate_uhid() -> str:
    """Generate UHID in format UHID-YYYYMMDD-XXXXXX"""
    date_str = datetime.utcnow().strftime("%Y%m%d")
    rand_part = secrets.token_hex(3).upper()  # 6 uppercase hex chars
    return f"UHID-{date_str}-{rand_part}"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uhid', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_uhid'), ['uhid'], unique=True)

    # Populate UHID for existing rows
    connection = op.get_bind()
    # Get all patients that don't have a UHID yet
    result = connection.execute(sa.text("SELECT id FROM patients WHERE uhid IS NULL"))
    rows = result.fetchall()

    for row in rows:
        patient_id = row[0]
        uhid = generate_uhid()
        # Make sure we have a unique UHID
        while connection.execute(
            sa.text("SELECT 1 FROM patients WHERE uhid = :uhid LIMIT 1"),
            {"uhid": uhid}
        ).first():
            uhid = generate_uhid()

        connection.execute(
            sa.text("UPDATE patients SET uhid = :uhid WHERE id = :id"),
            {"uhid": uhid, "id": patient_id}
        )

    connection.commit()

    # Now make the column NOT NULL
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('uhid',
                   existing_type=sa.String(),
                   nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_uhid'))
        batch_op.drop_column('uhid')

    # ### end Alembic commands ###
