"""add_note_type_to_clinical_notes

Revision ID: add_note_type_v1
Revises: add_uhid_column_v1
Create Date: 2026-03-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_note_type_v1'
down_revision: Union[str, None] = 'add_uhid_column_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_type', sa.Enum('intake', 'rounds', 'discharge', 'general', name='clinicalnotetype'), nullable=False, server_default='general'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.drop_column('note_type')
    # ### end Alembic commands ###
