"""initial_schema

Revision ID: d0b9eb7f28e4
Revises: 
Create Date: 2026-03-07 22:11:48.703500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b9eb7f28e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='audioprocessingstatus'), nullable=False))
        batch_op.add_column(sa.Column('celery_task_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audio_notes_celery_task_id'), ['celery_task_id'], unique=False)

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('relationship', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pending', 'active', 'declined', 'revoked', 'expired', name='consentstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_consents_action_token'), ['action_token'], unique=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_group', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comorbidities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('primary_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_policy_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mrn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('admission_type', sa.Enum('emergency', 'planned', 'transfer', name='admissiontype'), nullable=True))
        batch_op.add_column(sa.Column('patient_status', sa.Enum('admitted', 'in_observation', 'discharged', 'deceased', name='patientstatus'), nullable=True))
        batch_op.add_column(sa.Column('admission_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('discharge_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('discharge_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fall_risk', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_mrn'), ['mrn'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_mrn'))
        batch_op.drop_column('fall_risk')
        batch_op.drop_column('discharge_summary')
        batch_op.drop_column('discharge_at')
        batch_op.drop_column('admission_at')
        batch_op.drop_column('patient_status')
        batch_op.drop_column('admission_type')
        batch_op.drop_column('mrn')
        batch_op.drop_column('insurance_policy_no')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('primary_phone')
        batch_op.drop_column('medications')
        batch_op.drop_column('comorbidities')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('blood_group')

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_action_token'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'active', 'declined', 'revoked', 'expired', name='consentstatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('responded_at')
        batch_op.drop_column('requested_at')
        batch_op.drop_column('email_sent')
        batch_op.drop_column('action_token')
        batch_op.drop_column('contact_address')
        batch_op.drop_column('relationship')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_last_name')
        batch_op.drop_column('contact_first_name')

    with op.batch_alter_table('audio_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_notes_celery_task_id'))
        batch_op.drop_column('processing_error')
        batch_op.drop_column('celery_task_id')
        batch_op.drop_column('processing_status')

    # ### end Alembic commands ###
